source:
  type: postgresql
  host: db
  port: 5432
  database: spotify-fsd-next
  username: postgres
  password: pass1234

meilisearch:
  url: http://meilisearch:7700
  api_key: qyZz2qbX9Nleu20jKJa2Oe-GFJl-Tb-twF1rTn1mkz0

redis:
  url: redis://meilibridge-redis:6379

sync_tasks:
  - table: '"Track"'
    index: tracks
    primary_key: id
    full_sync_on_start: true