version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/share/nginx/html/static:ro # Твоя музыка/картинки
    depends_on:
      - frontend
      - backend

  db:
    image: bfontaine/postgres-wal2json:15-bookworm
    container_name: db
    command: postgres -c wal_level=logical
    ports: [ "5433:5432" ]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

#  redis:
#    image: redis:7-alpine
#    container_name: meilibridge-redis
#    ports:
#      - "6380:6379"
#    volumes:
#      - redis_data:/data
#    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

#  meilisearch:
#    image: getmeili/meilisearch:nightly
#    container_name: meilisearch
#    environment:
#      - MEILI_MASTER_KEY=qyZz2qbX9Nleu20jKJa2Oe-GFJl-Tb-twF1rTn1mkz0
#    ports:
#      - "7700:7700"
#    volumes:
#      - ./meili_data:/data.ms
#
#  meilibridge:
#    image: binarytouch/meilibridge:latest
#    restart: unless-stopped
#    command: [ "--config", "/config.yaml" ]
#    volumes:
#      - ./config.yaml:/config.yaml
#      - meilibridge-data:/data
#    ports:
#      - "7701:7701"
#    depends_on:
#      - db
#      - meilisearch
#      - redis



  backend:
    container_name: backend
    build:
      context: ./server
      target: development
    env_file:
      - ./server/.env
    environment:
      - CHOKIDAR_USEPOLLING=true # Важно для NestJS/Watch mode на Windows
      - WATCHPACK_POLLING=true
    volumes:
      - ./server:/app
      - ./static:/app/static
      - /app/node_modules
    ports: ["4000:4000"]
    depends_on: [db]

  frontend:
    container_name: frontend
    build:
      context: ./client
      target: development
    env_file:
      - ./client/.env
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      - WATCHPACK_POLLING=true
      - NEXT_TURBO_POLL=1000   # Экспериментальный флаг для некоторых версий 15.x/16.x
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next  # ЭТО РЕШИТ ПРОБЛЕМУ КОНФЛИКТА КЭША
      - ./static:/app/public/static:ro
    ports: ["3000:3000"]

volumes:
  redis_data:
  postgres_data:
  meilibridge-data: